### ISSUE TITLE
Redirect on View/Edit Cluster Config when there is a redirect in kong

### ISSUE THREAD

**Issue by cronventis** [yesinteractive/kong-map#13]
So I added a plugin to one of my routes to do ra request termination with these settings:

```
config:
  status_code: 301
  content_type: "text/html"
  body: "<meta http-equiv=\"refresh\" content=\"0; URL='https://domain.de/target/'\" />"
```

When clicking on "View/Edit Cluster Config" in KongMap, I get the loading screen and at one point during load, I get redirected to "https://domain.de/target" just like it is defined in the plugin..
