### ISSUE TITLE
Do not see entity in kongmap that is visible in Kong Manager

### ISSUE THREAD

**Issue by avik-sengupta-kong** [yesinteractive/kong-map#25]
Kongmap config
`{"my enterprise cluster":{"kong_admin_api_url":"http://api.kong.lan:8001/","kong_edit_config":"false","kong_ent":"true","kong_ent_token":"***","kong_ent_token_name":"kong-admin-token","kong_ent_manager_url":"http://manager.kong.lan:8002/"}}`

Docker-compose 
```
kongmap:
    image: docker.io/yesinteractive/kongmap
    container_name: kongmap
    networks:
      - demo-net
    environment:
      - KONGMAP_CLUSTERS_JSON=$KONG_CLUSTERS
      - KONGMAP_URL=http://api.kong.lan:8100
    restart: always
    ports:
      - "8100:8100"
      - "8143:8143"
```
![image](https://user-images.githubusercontent.com/83654231/155135187-95060890-3b01-4d65-93a1-f04ae1d023cc.png)

![image](https://user-images.githubusercontent.com/83654231/155135128-1346f965-56e8-47c5-88c3-58913c918b72.png)
