### ISSUE TITLE
Kongmap Configuration with Kong Error

### ISSUE THREAD

**Issue by koushikraghu1297** [yesinteractive/kong-map#27]
I have tried deploying kong-map as a pod in one namespace of kubernetes.

I intend to configure kongmap behind kong with basic auth enabled to it.
Before i enable the basic auth plugin i have added kongmap svc and a route to the kong-admin , below are the configurations -

```
_format_version: "1.1"
consumers:
- basicauth_credentials:
  - password: <pwdforkongmap>
    username: kongmap
  custom_id: kongmap
  username: kongmap
services:
- connect_timeout: 60000
  host: kongmap-svc.kong.svc.cluster.local
  name: kongmapsvc
  path: /             // I have tried different path as well like /0 , /$ etc...
  port: 80         // changed the access port to 80 in k8s svc object. Able to access kongmap via ELB
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: kongmaproute
    path_handling: v1
    paths:
    - /0,/$                // I have tried different paths as well like  /0 , /$ , /kongmap , /  etc...
    preserve_host: true              // also tried disabling and enabling in combination with strip_path
    protocols:
    - http
    - https
    regex_priority: 1
    request_buffering: true
    response_buffering: true
    strip_path: false       // also tried disabling and enabling in combination with preserve_host
  write_timeout: 60000
```
When i try to access my kongmap via kong-proxy endpoint …
i am getting
`{"message":"no Route matched with those values"}`

And since the url of kongmap changes dynamically on Ui access to different internal routes -
like /0 or /deck/edit/0/0 on edit configs… How do we configure this dynamically in kong end for routes and svc.

Could you please help me on what i am actually missing here…
